### ISSUE TITLE
Dark Mode Theme Icon Not Working With Latest Update

### ISSUE THREAD

**Issue by SandmanPSU** [igorlogius/copy-taburls-html#3]
After the most recent update "update workflow + cleanup + add multi url copy", I noticed that the icon moved from the URL entry area to a Toolbar button, and with this move the icon no longer is appearing as white for a dark mode. It is back to black, and this revert may have to do with the fact that the background color now is a slightly lighter gray.
![image](https://user-images.githubusercontent.com/108283599/187177655-e824d078-d37e-45c9-ac24-20847bc33e51.png)

This is Firefox Browser 104.0 (64-bit).

**Comment by igorlogius** [comment]
@SandmanPSU  
Thanks for letting me know. 

It might have made a mistake or the icons for the browserAction behave differently.
i'll look into that. 

PS: 
Also as a short explaination ... i moved the icon into the toolbar area, because of 2 reason

1. You can now copy multiple urls (of selected tabs) , so the button action is not entirely page bound anymore
2. pageAction isnt/wont be supported for mobile devices and i thought that it would be nice if it worked there too (to a degree at least).

**Comment by igorlogius** [comment]
@SandmanPSU , should be working now. If not, let me know and i'll take another look

**Comment by SandmanPSU** [comment]
I see the update and it looks good. Thanks.
